@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NzI4NTYxNTd9.Z8AnczK1Dl7UGWSAS3kqdKFRO5Ces1xxpTzHqjab8fg

######################################
### Activity Index
GET http://localhost:3000/activities.json

### Activity Show
GET http://localhost:3000/activities/4.json

### Activity Create
POST http://localhost:3000/activities.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "code",
  "user_id": "10"
}

### Activity Update
PATCH http://localhost:3000/activities/8.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "selected": "true"
}

### Activity Destroy
DELETE http://localhost:3000/activities/10.json
Authorization: Bearer {{jwt}}

######################################
### Did_It Index
GET http://localhost:3000/did_its.json

### Did_It Show
GET http://localhost:3000/did_its/5.json

### Did_It Create
POST http://localhost:3000/did_its.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": "3",
  "activity_id": "7",
  "date": "2022-12-28"
}

### Did_It Destroy
DELETE http://localhost:3000/did_its/62.json
Authorization: Bearer {{jwt}}

######################################
### User Index
GET http://localhost:3000/users.json

### User Show
GET http://localhost:3000/users/3.json

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test3",
  "email": "test2@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### User Update
PATCH http://localhost:3000/users/3.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "streak": 1
}

### User destroy
DELETE http://localhost:3000/users/5.json
Authorization: Bearer {{jwt}}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "check@test.com",
  "password": "password"
}